# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shopping_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setStyleSheet("\n"
"      QWidget {\n"
"        background-color: #e6f2ff;\n"
"      }\n"
"      QLabel {\n"
"        color: #000000;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"      }\n"
"      QLineEdit {\n"
"        border: 2px solid #4682b4\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        font-size: 13px;\n"
"        color: #000000;\n"
"        background-color: #000000\n"
"      }\n"
"      QlineEdit:placeholder {\n"
"        color: #000000\n"
"      }\n"
"\n"
"      QCheckbox {\n"
"        font-size: 14px;\n"
"        margin: 5px;\n"
"        color: #000000;\n"
"        font-weight: bold;\n"
"      }\n"
"      QPushButton {\n"
"        background-color: #000000;\n"
"        color: #2e7d32;\n"
"        border: 2px solid #2e7d32;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"      }\n"
"      QPushButton:hover {\n"
"        background-color: #e8f5e9;\n"
"      }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.address_label = QtWidgets.QLabel(Form)
        self.address_label.setObjectName("address_label")
        self.verticalLayout.addWidget(self.address_label)
        self.address_input = QtWidgets.QLineEdit(Form)
        self.address_input.setObjectName("address_input")
        self.verticalLayout.addWidget(self.address_input)
        self.phone_label = QtWidgets.QLabel(Form)
        self.phone_label.setObjectName("phone_label")
        self.verticalLayout.addWidget(self.phone_label)
        self.phone_input = QtWidgets.QLineEdit(Form)
        self.phone_input.setObjectName("phone_input")
        self.verticalLayout.addWidget(self.phone_input)
        self.food_label = QtWidgets.QLabel(Form)
        self.food_label.setObjectName("food_label")
        self.verticalLayout.addWidget(self.food_label)
        self.food_checkbox_layout = QtWidgets.QVBoxLayout()
        self.food_checkbox_layout.setObjectName("food_checkbox_layout")
        self.verticalLayout.addLayout(self.food_checkbox_layout)
        self.order_button = QtWidgets.QPushButton(Form)
        self.order_button.setObjectName("order_button")
        self.verticalLayout.addWidget(self.order_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.address_label.setText(_translate("Form", "ჩაწერე მისამართი:"))
        self.phone_label.setText(_translate("Form", "შეიყვანე ტელეფონის ნომერი:"))
        self.phone_input.setPlaceholderText(_translate("Form", "მაგ: 555123456"))
        self.food_label.setText(_translate("Form", "აირჩიე საკვები:"))
        self.order_button.setText(_translate("Form", "შეუკვეთე"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
